### ISSUE TITLE
Configurable non-hardcoded newline?

### ISSUE THREAD

**Issue by joshtriplett** [JoshMcguigan/libps1#2]
libps1 currently [hardcodes the `\n` before the last character of the prompt](https://github.com/JoshMcguigan/libps1/blob/dbe98d3f9ef2dddb2a875e9037637ce85240476d/src/lib.rs#L106). Would you consider providing a compile-time `Option<&'static str>` for that, so that it can be removed (`None`) or changed to a space (`Some(" ")`)?

**Comment by joshtriplett** [comment]
Note that this will require #3 so that bash will understand the width of the prompt.

**Comment by JoshMcguigan** [comment]
First off, thanks for all of your feedback. I appreciate you making separate issues for them as well, so they can be tracked individually. I'd certainly like to add this configuration option, and I agree it is blocked (hopefully not for long) by #3. 

As for the `Option<&'static str>`, is there a reason you prefer this to just a `&'static str`? In that case, it can still default to `\n`, but a user could overwrite with `""` (empty string), `" "` (single whitespace), or whatever they prefer. Or perhaps even simpler, pista just had a boolean to optionally include the newline. Is there a benefit to the additional flexibility (and minor complexity) of using a string rather than a boolean to configure this?

**Comment by joshtriplett** [comment]
@JoshMcguigan Good point, an empty string is quite sufficient, and an `Option` isn't needed. I think I started out imagining `Option<char>`, then realized a `&'static str` would be preferable to allow multiple characters, and didn't at that point consider how that made`Option` unnecessary.

I do think a space still makes sense, to visually separate the git-related symbols from the final prompt character. I could imagine someone using an empty string, a space, multiple spaces, a space and a Unicode symbol they like (`🦀`), a newline, or any combination of those.
